version: '3.7'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: landing-page
    build:
      context: ./docker/dockerfiles
      dockerfile: php83.Dockerfile
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
        UNAME: ${HOST_UNAME}
        USERNAME: ${LOGIN_USERNAME}
    volumes:
      - ./:/var/www/html
  db:
    image: mariadb:11.1
    restart: always
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: db
      MARIADB_ROOT_PASSWORD: maymunki
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=maymunki
  mailer:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
volumes:
  db:
